# Generated by Django 4.1.5 on 2023-01-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.RemoveField(
            model_name='username',
            name='watch',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
