# Generated by Django 4.1.5 on 2023-01-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumAdN', models.CharField(max_length=50, unique=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, verbose_name=' Sélectionner le sexe ')),
                ('DateNaissance', models.DateField(null=True)),
                ('HeureNaissance', models.TimeField(null=True, verbose_name='heure de naissance')),
                ('annee', models.CharField(default='', editable=False, max_length=4)),
                ('LieuNaissance', models.CharField(max_length=50)),
                ('PaysNaissance', models.CharField(max_length=50)),
                ('NomPrenomPere', models.CharField(max_length=50, verbose_name='Nom et Prenom du Pere')),
                ('DateNPere', models.DateField(verbose_name='Entrez la date de naissance du Pére')),
                ('LieuNPere', models.CharField(max_length=50, verbose_name='Entrez le lieu de naissance du Pére')),
                ('ProfessionPere', models.CharField(max_length=50, verbose_name='Entrez la profession du Pére')),
                ('NomPrenomMere', models.CharField(max_length=50, verbose_name='Entrez le Nom et Prénom de la Mére')),
                ('DateNMere', models.DateField(verbose_name='Entrez la date de naissance de la Mére')),
                ('LieuNMere', models.CharField(max_length=50, verbose_name='Entrez le lieu de naissance de la Mére')),
                ('ProfessionMere', models.CharField(max_length=50, verbose_name='Entrez la profession de la Mére')),
                ('NomPrenomGPP', models.CharField(max_length=50, verbose_name='Entrez le Nom et Prénom grandPére Paternel')),
                ('NomPrenomGPM', models.CharField(max_length=50, verbose_name='Entrez le Nom et Prénom grandPére Maternel')),
                ('NomPrenomGMP', models.CharField(max_length=50, verbose_name='Entrez le Nom et Prénom grandMére Paternel')),
                ('NomPrenomGMM', models.CharField(max_length=50, verbose_name='Entrez le Nom et Prénom grandMére Maternel')),
            ],
        ),
        migrations.CreateModel(
            name='BureauEtatCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estConsulat', models.BooleanField(default=False)),
                ('Commune', models.CharField(max_length=30)),
                ('Daira', models.CharField(max_length=30)),
                ('Wilaya', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('Commune', 'Daira', 'Wilaya')},
            },
        ),
        migrations.CreateModel(
            name='RegistreMariages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Année', models.CharField(max_length=4)),
                ('Bureau10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bureauetatcivil')),
            ],
        ),
        migrations.CreateModel(
            name='RegistreNaissances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Année', models.CharField(max_length=4)),
                ('Bureau0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bureauetatcivil')),
            ],
        ),
        migrations.CreateModel(
            name='RegistreDecés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Année', models.CharField(max_length=4)),
                ('Bureau20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bureauetatcivil')),
            ],
        ),
        migrations.CreateModel(
            name='OfficierEtatCivil',
            fields=[
                ('matricule', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('datePriseService', models.DateField(null=True)),
                ('estMaire', models.BooleanField(default=False)),
                ('Bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.bureauetatcivil')),
                ('user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumAdD', models.CharField(max_length=50, null=True, verbose_name='Numéro denregistrement de Deces')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('dateD', models.DateField(max_length=4, null=True)),
                ('JourDeces', models.CharField(max_length=15)),
                ('HeureDeces', models.CharField(max_length=2)),
                ('LieuDeces', models.CharField(max_length=50)),
                ('Sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=50)),
                ('Marie', models.CharField(max_length=50)),
                ('annee', models.CharField(default='', editable=False, max_length=4)),
                ('NumAdN', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.birth')),
                ('NumRegDeces', models.ManyToManyField(max_length=50, to='event.registredecés')),
            ],
        ),
        migrations.AddField(
            model_name='birth',
            name='NumRegNais',
            field=models.ManyToManyField(to='event.registrenaissances', verbose_name='Entrez le Numero du registre de naissance'),
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumAdM', models.CharField(max_length=50, verbose_name='Numéro d’enregistrement du mariage')),
                ('LieuMariage', models.CharField(max_length=50)),
                ('DateMariage', models.DateField(null=True)),
                ('ProfessionF', models.CharField(default='', max_length=50, verbose_name='Entrez la profession de la Femme')),
                ('ProfessionH', models.CharField(default='', max_length=50, verbose_name='Entrez la profession de lHomme')),
                ('Domicile', models.TextField(default='', max_length=50)),
                ('NPTemoin1', models.CharField(default='', max_length=50, verbose_name='Entrez le Nom et Prénom du temoin1')),
                ('NPTemoin2', models.CharField(default='', max_length=50, verbose_name='Entrez le Nom et Prénom du temoin2')),
                ('NumRegMar', models.ManyToManyField(to='event.registremariages', verbose_name='Entrez le Numero du registre du mariage')),
                ('acteNaissEpse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='naissEpse', to='event.birth')),
                ('acteNaissEpx', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='naissEp', to='event.birth')),
            ],
            options={
                'unique_together': {('acteNaissEpx', 'acteNaissEpse')},
            },
        ),
    ]
