# Generated by Django 4.1.5 on 2023-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='NumAdN',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro d’enregistrement'),
        ),
    ]
