# Generated by Django 4.1.5 on 2023-01-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_birth_numadn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='annee',
            field=models.CharField(default='', max_length=4),
        ),
    ]
