# Generated by Django 4.1.5 on 2023-01-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_birth_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='NumAdN',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.birth', verbose_name='Numéro denregistrement'),
        ),
    ]
