# Generated by Django 4.1.5 on 2023-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_death_numadn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='annee',
            field=models.CharField(default='', max_length=4),
        ),
    ]
