# Generated by Django 4.1.5 on 2023-01-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_death_annee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registredecés',
            old_name='Bureau20',
            new_name='Bureau2',
        ),
        migrations.RenameField(
            model_name='registremariages',
            old_name='Bureau10',
            new_name='Bureau1',
        ),
    ]
